// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqgflhkrcjgbmedeecog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZ2ZsaGtyY2pnYm1lZGVlY29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzI2NTAsImV4cCI6MjA3MTAwODY1MH0.w1YFWMYpFr_MW18ATr4FdyWOrwaB9yPYd1wkt8diQY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});